### PR TITLE
Adding an API options to separate fetching client's authentication fr…

### PR DESCRIPTION
**Pull request by Ethan-Yami**
…om FAS single api-aes-https.php file

Some codes are added below:

conf.c // adding some API parameters options
conf.h // adding some API default values
main.c // Delivering the API option to authmon.sh

### CODE REVIEW

**Comment by bluewavenet** [comment]
@Ethan-Yami 
openNDS:master is currently at version 9.0.1beta

You need to fetch and rebase origin for Ethan-Yami:master

**Comment by bluewavenet** [comment]
@Ethan-Yami 
We should extend the use of `option themespec_path` for this purpose instead of adding another config option (this was my original intention for the next release)

**Comment by bluewavenet** [comment]
@Ethan-Yami 
All we need to do in openNDS is add themespecpath to the encoded query string that is sent to the FAS.
The FAS will then know what to include for the frontend.

**Comment by Ethan-Yami** [comment]
@bluewavenet  Yes, I understand. We should extend the use of option themespec_path for front end to specify which template need to use.

But I think this opthin themespec_path  is the same thing as the faspath,because we can put static html file in the faspath,such as index.html, index.php..

But for backend,we might use a different domain name, and front end use a CDN network . 
example:

FAS-----front end 

https://portal.cloudwifi.io/themes/airport/

fqdn:portal.cloudwifi.io
faspath:/themes/airport/
filename: index.html | index.php

tips:We can use ajax to call backend system provide api to write a log file to wait openNDS reading.
 

FAS-----Backend  


https://api.cloudwifi.io/users/verify/

fqdn:api.cloudwifi.io
faspath:/themes/airport/
filename: index.php

Or both Front end backend we can use the same domain name...

**Comment by bluewavenet** [comment]
@Ethan-Yami 
But:
I think you have it the wrong way around. fasfqdn/faspath should point to a new standard FAS library backend that picks up themespecpath from the encoded query string.

themespecpath could point to a file local to the FAS, or could point to a file on some other server in the walled garden.
openNDS could even automate the walled garden addition by parsing themespecpath.

A small but important point - It is important that no assumptions are made at the openNDS end about the language used for the FAS.

**Pull request closed without merging**
