### PR TITLE
Add 'Documentation=man:opennds' to unit section of service file.

### PR DESCRIPTION
**Pull request by dzatoah**
This PR adds 'Documentation=man:opennds' to unit section of service file.

### CODE REVIEW

**Comment by bluewavenet** [comment]
This is Debian specific and will not work for other distros. See my comments on #341

**Comment by sunweaver** [comment]
@bluewavenet The Documentation=man:<manpage> is not Debian-specific.

See https://www.freedesktop.org/software/systemd/man/systemd.unit.html

(which is the upstream documentation and it lists the "man:" prefix as valid prefix).

**Comment by bluewavenet** [comment]
@sunweaver 

> The Documentation=man: is not Debian-specific.

This is true, but
`Documentation=man:opennds`
**is** Debian specific because the man page is only generated for Debian.

The best way forward is to remove the linux_debian/doc folder from the source.

**Comment by sunweaver** [comment]
Ah, specific to your Debian package build recipe. Now I understand. Why don't you ship the man page as part of the openNDS upstream code. Man pages are not Debian-specific, but useful on most other distros, as well.

**Comment by bluewavenet** [comment]
The Debian specific man page is now removed. See PR #346

**Pull request closed without merging**
