### PR TITLE
Add some cosmetic

### PR DESCRIPTION
**Pull request by dianariyanto**
Add some CSS style to the default splash page to look fresher.
mockDrop_Nexus 6 in front of a iMac

[Screenshot 1](https://user-images.githubusercontent.com/7848056/170845429-08a57be2-9efc-4677-a961-72c82531ca45.jpg)
[Screenshot 2](https://user-images.githubusercontent.com/7848056/170845507-4dedecb9-41d3-4bad-ba4c-15acca3c702a.jpg)
[Screenshot 3](https://user-images.githubusercontent.com/7848056/170845510-3363bce3-3da2-403b-be81-e67b6140d8cb.jpg)
[Screenshot 4](https://user-images.githubusercontent.com/7848056/170845513-a454c3fe-4bc3-4436-9186-d3a9f1215e46.jpg)

### CODE REVIEW

**Comment by bluewavenet** [comment]
@dianariyanto 
Thank you! Sorry for the long delay replying - I have been very busy!

I tried it on numerous screen sizes and it looks good.

A couple of points:
 * We have a general policy to use tabs for indentation rather than space(s)
 * The css will need to be changed where it is embedded in the example FAS php scripts (fas-hid.php, fas-aes.php and fas-aes-https.php). You will find this in `function insert_css()`

**Comment by bluewavenet** [comment]
@dianariyanto 
It is purely my personal preference but I would like to see `border: 2px solid #aaa;` reinstated into `.insert { }`
I think it looks better with the solid border, but convince me it shouldn't be there :-D

I'll test the fas scripts ;-)

**Comment by dianariyanto** [comment]
I'm not testing the FAS, please let me know if it does not break the default look. 

I think wrapper with some border also looks cool, how about ```border: 2px solid rgba(350, 350, 350, 0.9);``` ?

**Comment by bluewavenet** [comment]
No border shows up with `border: 1px solid rgba(350, 350, 350, 0.9);`
But with `border: 2px solid #aaa;` I get:

Screenshot 2022-06-08 at 09-41-30 BlueWaveOpenWiFi S N 9483c404dfdd Client Session Status

**Comment by dianariyanto** [comment]
Look fresh and good @bluewavenet i will re-insert ```border: 2px solid #aaa;``` to the code.

**Comment by bluewavenet** [comment]
> i will re-insert border: 2px solid #aaa; to the code.

Don't forget the fas scripts ;-)

I tested with fas-aes and it works fine as expected.

**Comment by bluewavenet** [comment]
Thank you very much for your efforts.
Looks good.

**Pull request merged**
