### PR TITLE
Fix - NULL pointer segfault in microhttpd on preauth

### PR DESCRIPTION
**Pull request by dddaniel**
Signed-off-by: Daniel Danzberger <daniel@dd-wrt.com>

### CODE REVIEW

**Comment by bluewavenet** [comment]
@dddaniel 
A good point. Although it is good practice for there always to be an "Accept:" header, it is certainly not guaranteed.
This fix should be applied after every call to the get_accept_callback iterator, ie function authenticated as wall as function preauthenticated.

Your knowledge of "C" is probably much greater than mine, but is:
`if (accept && strcmp(accept, "application/captive+json") == 0) {`

always the same as:
```
if (accept) {
   if (strcmp(accept, "application/captive+json") == 0) {
```
regardless of the compiler used?
ie In the combined "if" statement, can we guarantee the second test is only done if the first test is true?
Could it not be interpreted as "do both tests then check if both are true" ?
Just my Obsessive Compulsive thought patterns being triggered ;-D

**Comment by dddaniel** [comment]
> `if (accept && strcmp(accept, "application/captive+json") == 0) {`
> 
> always the same as:
> 
> ```
> if (accept) {
>    if (strcmp(accept, "application/captive+json") == 0) {
> ```
> 
> regardless of the compiler used?
> ie In the combined "if" statement, can we guarantee the second test is only done if the first test is true? Could it not be interpreted as "do both tests then check if both are true" ?

Yes, this statement is safe regardless of the compiler used.
'&&' will always branch out when the first parameter is false.

**Comment by dddaniel** [comment]
> A good point. Although it is good practice for there always to be an "Accept:" header, it is certainly not guaranteed.

I noticed this on my iphone 8 with the latest IOS version. Never had that before.

**Comment by bluewavenet** [comment]
@dddaniel 
I will add the fix to the other place it is needed. We can then complete pre release testing.
Thank you!

**Pull request merged**
