### PR TITLE
Workflows: test commit formalities

### PR DESCRIPTION
**Pull request by systemcrash**
some github workflows to automate checks

### CODE REVIEW

**Review by bluewavenet — COMMENTED** [review]
FYI: openNDS on Github used to have a full workflow CI, including compilation testing.
But as BlueWave is a commercial company, Github decided to charge an unreasonable amount for the service, so it was removed.

**Comment by systemcrash** [comment]
Meh. Hosted runner?

**Comment by bluewavenet** [comment]
@systemcrash 

> Meh. Hosted runner?

Suggestions?
We do it all in house then push to Github - which is fine for internal dev work....

**Comment by systemcrash** [comment]
Convert openNDS to an opensource org? Vaguely aware such options exist in github. Everything hosted on it is OS anyway, right?

**Comment by bluewavenet** [comment]
@systemcrash 

> opensource

openNDS is an opensource organisation, but BlueWave is a commercial organisation. This is fine with Github but means there are fees that get charged. There is no problem with that as such. But it would be an unnecessary expense, given that full CI is done internally as well as the full OpenWrt CI that happens with a new release. Yes sure if there were many outside contributors there would be numerous possible solutions.
As it stands, there is not much extra for contributors to do, so it is not in any way an impediment.

**Pull request closed without merging**
