### PR TITLE
Formatting improvements

### PR DESCRIPTION
**Pull request by systemcrash**
more consistent 'Default' values
re-ordered up>download
custom FAS options relocated
more consistent structure
less scattered

### CODE REVIEW

**Comment by bluewavenet** [comment]
@systemcrash 
Thank you for your efforts on this, you have clearly spent some time on it and it is much appreciated.

However, a single PR with a single commit encompassing ALL the changes makes reviewing arduous and time consuming.
A quick scan shows many valid improvements. But I can also see many changes that are perhaps more personal preference and would benefit from, at least, a little discussion.

I would prefer to see separate PRs for each of the headings in your description, each submitted and reviewed before submitting the next.

ie PRs entitled something like this:

1. [documentation] more consistent 'Default' values
2. [documentation] re-ordered up>download
3. [documentation] custom FAS options relocated
4. [documentation] more consistent structure
5. [documentation] less scattered

**Review by bluewavenet — CHANGES_REQUESTED** [review]
> Move custom params to FAS

What is the reasoning for this change?

**Review by bluewavenet — CHANGES_REQUESTED** [review]
> move fasport after fasremoteip

Why?

**Comment by systemcrash** [comment]
> > Move custom params to FAS
> 
> What is the reasoning for this change?

Because they all start `fas_custom_`



> > move fasport after fasremoteip
> 
> Why?

FQDN > IP > Port > Path

Standard order within a URI

**Comment by bluewavenet** [comment]
@systemcrash 
The changes seem to be cosmetic as far as I can see, but you have not provided any reasoning for each change.

Please note my previous comment where I suggested a method for making review/discussion much easier:

> I would prefer to see separate PRs for each of the headings in your description, each submitted and reviewed before submitting the next.
> 
> ie PRs entitled something like this:
> 
> 1. [documentation] more consistent 'Default' values
> 2. [documentation] re-ordered up>download
> 3. [documentation] custom FAS options relocated
> 4. [documentation] more consistent structure
> 5. [documentation] less scattered
> 

As it stands this process would be very time consuming and without proper review, errors and/or misconceptions could creep in. Your efforts are appreciated, but I will close this and suggest you follow my suggested method.

**Pull request closed without merging**
